# Generated by Django 5.0.6 on 2024-06-01 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketingModule', '0002_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPorCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpoDelCorreo', models.TextField()),
                ('tipoCorreo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingPorCorreoPersonal',
            fields=[
                ('marketingporcorreo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MarketingModule.marketingporcorreo')),
                ('emailDeDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketingModule.contact')),
            ],
            bases=('MarketingModule.marketingporcorreo',),
        ),
    ]
