# Generated by Django 5.0.6 on 2024-06-01 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketingModule', '0003_marketingporcorreo_marketingporcorreopersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampañaDeMarketing',
            fields=[
                ('marketingporcorreo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MarketingModule.marketingporcorreo')),
                ('nombre', models.CharField(max_length=100)),
                ('numeroDeIntegrantes', models.PositiveIntegerField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketingModule.group')),
            ],
            bases=('MarketingModule.marketingporcorreo',),
        ),
    ]
